### ISSUE TITLE
Error - First install from Server

### ISSUE THREAD

**Issue by Nickous** [VivumLab/VivumLab#320] opened 2021-01-22 13:30 UTC
I just want to install VivumLab **from a server**.
(I would like to use later the Client computer with deploy to a server, when I'll be more familiar...!)
But is install FROM server working?
Many tries last days...and never succeeded with basic setup.
I opened older post on Zulip. I don't know if it's better here?

Today, I'm stuck with a Ansible Playbook command returned with an error code.
I don't know what is wrong? my settings?

**To Reproduce**
1. DigitalIOcean fresh install Debian 10 (SSHkey, login root)
2. update / upgrade / install git curl / install docker using the convenience script
3. `git clone --branch master https://github.com/VivumLab/VivumLab.git`
4. `cd Vivumlab`
4. `./launch.sh`
5. `vlab deploy`
4. See error `Ansible Playbook command returned with an error code.`

**Screenshots**
![2021_01_22_13_14_38_DigitalOcean_DO1_Droplet](https://user-images.githubusercontent.com/10545977/105492621-7dd85700-5cb8-11eb-8761-9739041f6c56.png)

**Server**
 - OS: [Debian 10]
 - Vivumlab Version: [v1.1.1]

**Comment by voryzen** [comment] 2021-01-27 01:47
+1
"No authenticationmethods avaiable" error

**Comment by codefriar** [comment] 2021-01-27 03:53
no authentication methods available means Ansible was unable to authenticate to your server. 

I suspect but can't confirm Debian's ssh config doesn't listen on 127.0.0.1 and / or you don't have key based ssh authentication working.

**Comment by codefriar** [comment] 2021-01-27 04:19
@Nickous, @voryzen  Ok. I just followed your instructions to reproduce. Here's what I found.

1. I had to use the public ip, not 127.0.0.1 for the vlab_ip. 
2. The only way I could duplicate this was to attempt to deploy when there is no valid id_rsa (or whatever key is specified in the config) available. 

I think the breakdown here is that you setup key based ssh from your laptop to your digital ocean droplet. Digital ocean makes this easy. However! when you let digital ocean do this, it only copies/sets the public key, not the private key. 

This means you can ssh with a key from your laptop to the digital ocean droplet, but you can't ssh from the server to the server via the public IP address, because the private key isn't there. 

You can test this by running 

```ssh root@104.236.52.109 -I ~/.ssh/id_rsa.pub```
(note, your key may be different)

after a failed deployment, you'll see something like this:

```
ssh root@104.236.52.109 -I ~/.ssh/id_rsa.pub
dlopen /root/.ssh/id_rsa.pub failed: /root/.ssh/id_rsa.pub: cannot read file data: Is a directory
load pubkey "/root/.ssh/id_rsa": invalid format
The authenticity of host '104.236.52.109 (104.236.52.109)' can't be established.
```

These 'files' are directories, because that's what docker does when it can't mount a non-existent file. 

While I'd ultimately like to guard against this problem, this is not the standard install use case and so its likely a low-priority fix. I'm closing this issue, feel free to open a different one, if you have further difficulties after setting up key based ssh from the deploying machine to the server machine which in this case is from your droplet to your droplet.

**Closed by codefriar** 2021-01-27 04:19 UTC
