### ISSUE TITLE
Bug: pre-commit is required on the client

### ISSUE THREAD

**Issue by robjloranger** [VivumLab/VivumLab#126] opened 2020-10-30 01:17 UTC
**Describe the bug**
The client running vlab requires the python tool `pre-commit` to be installed. This should be listed in the requirements with Docker, or somehow managed without making changes to the client machine.

**To Reproduce**
1. On a computer without previously installing `pre-commit`, run `./vlab config`

**Expected behavior**
Configuration runs without error.

**Desktop (please complete the following information):**
 - OS: Client - Manjaro i3
 - Service: n/a
 - Vivumlab Version: v0.3.0

**Additional context**
Error:

```
Creating an empty config file
Creating an empty Vault
Creating ansible_bash.vars file
/home/robbie/code/VivumLab/VivumLab/tasks/SanityCheckTasks.sh: line 127: pre-commit: command not found
--- Stack trace from shell process 246311 depth=1 -------------
Failed command: pre-commit --version
Return status: 127

File /home/robbie/code/VivumLab/VivumLab/tasks/SanityCheckTasks.sh, line 127, in Task::check_for_precommit ()
File /home/robbie/code/VivumLab/VivumLab/tasks/SanityCheckTasks.sh, line 11, in Task::sanity_check_local ()
File /home/robbie/code/VivumLab/VivumLab/tasks/CoreTasks.sh, line 18, in Task::logo_local ()
File /home/robbie/code/VivumLab/VivumLab/tasks/ConfigTasks.sh, line 14, in Task::config ()
File ./vlab, line 721, in _taskit_run_task_with_args ()
File ./vlab, line 653, in taskit_run ()
File ./vlab, line 926, in taskit_main ()
File ./vlab, line 938, in main ()
--- Stack trace from shell process 246112 depth=0 -------------
Failed command: pcver=$(pre-commit --version)
Return status: 127

File /home/robbie/code/VivumLab/VivumLab/tasks/SanityCheckTasks.sh, line 127, in Task::check_for_precommit ()
File /home/robbie/code/VivumLab/VivumLab/tasks/SanityCheckTasks.sh, line 11, in Task::sanity_check_local ()
File /home/robbie/code/VivumLab/VivumLab/tasks/CoreTasks.sh, line 18, in Task::logo_local ()
File /home/robbie/code/VivumLab/VivumLab/tasks/ConfigTasks.sh, line 14, in Task::config ()
File ./vlab, line 721, in _taskit_run_task_with_args ()
File ./vlab, line 653, in taskit_run ()
File ./vlab, line 926, in taskit_main ()
File ./vlab, line 938, in main ()
```

**Comment by voryzen** [comment] 2020-10-30 03:51
This is not a bug. pre-commit is there so that users developing for/ with Vivumlab contribute clean code to the project.

Pre-commit, perhaps, should not be present with the master branch. However, it's presence on the dev branch is intentional; as such, this is not a bug.

If you agree that pre-commit should be exempt from the master branch, recreate this issue as a feature request, stating the intentions.

Closing issue..

**Closed by voryzen** 2020-10-30 03:51 UTC
Labels: bug
